# -*- coding: utf-8 -*-
"""Template_ASMR_TRANSLATION.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MJXaWy-JHxA1OnCANQ5RQXmmVywiQHum

# Click here below to attach files ⬇️
"""

from google.colab import drive
drive.mount('/content/drive')

"""

```

```
# Translation template for ASMR subtitles



---


**🚨** Enable **Hardware acceleration** with GPU in `"Runtime environment" > "Change runtime type"`








"""

#@title ⚙️ Run this shield to install the librarys.
"""
references:
https://blog.addpipe.com/recording-audio-in-the-browser-using-pure-html5-and-minimal-javascript/
https://stackoverflow.com/a/18650249
https://hacks.mozilla.org/2014/06/easy-audio-capture-with-the-mediarecorder-api/
https://air.ghost.io/recording-to-an-audio-file-using-html5-and-js/
https://stackoverflow.com/a/49019356
"""
!pip install stable-ts
!pip install jiwer
!pip install ffmpeg
!pip install git+https://github.com/openai/whisper.git
!pip install jiwer
!pip install ffmpeg

from IPython.display import HTML, Audio
from google.colab.output import eval_js
from base64 import b64decode
import numpy as np
from scipy.io.wavfile import read as wav_read
import io
import ffmpeg

AUDIO_HTML = """
<script>
var my_div = document.createElement("DIV");
var my_p = document.createElement("P");
var my_btn = document.createElement("BUTTON");
var t = document.createTextNode("Press to start recording");

my_btn.appendChild(t);
//my_p.appendChild(my_btn);
my_div.appendChild(my_btn);
document.body.appendChild(my_div);

var base64data = 0;
var reader;
var recorder, gumStream;
var recordButton = my_btn;

var handleSuccess = function(stream) {
  gumStream = stream;
  var options = {
    //bitsPerSecond: 8000, //chrome seems to ignore, always 48k
    mimeType : 'audio/webm;codecs=opus'
    //mimeType : 'audio/webm;codecs=pcm'
  };
  //recorder = new MediaRecorder(stream, options);
  recorder = new MediaRecorder(stream);
  recorder.ondataavailable = function(e) {
    var url = URL.createObjectURL(e.data);
    var preview = document.createElement('audio');
    preview.controls = true;
    preview.src = url;
    document.body.appendChild(preview);

    reader = new FileReader();
    reader.readAsDataURL(e.data);
    reader.onloadend = function() {
      base64data = reader.result;
      //console.log("Inside FileReader:" + base64data);
    }
  };
  recorder.start();
  };

recordButton.innerText = "Recording... press to stop";

navigator.mediaDevices.getUserMedia({audio: true}).then(handleSuccess);


function toggleRecording() {
  if (recorder && recorder.state == "recording") {
      recorder.stop();
      gumStream.getAudioTracks()[0].stop();
      recordButton.innerText = "Saving the recording... pls wait!"
  }
}

// https://stackoverflow.com/a/951057
function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

var data = new Promise(resolve=>{
//recordButton.addEventListener("click", toggleRecording);
recordButton.onclick = ()=>{
toggleRecording()

sleep(2000).then(() => {
  // wait 2000ms for the data to be available...
  // ideally this should use something like await...
  //console.log("Inside data:" + base64data)
  resolve(base64data.toString())

});

}
});

</script>
"""

def get_audio():
  display(HTML(AUDIO_HTML))
  data = eval_js("data")
  binary = b64decode(data.split(',')[1])

  process = (ffmpeg
    .input('pipe:0')
    .output('pipe:1', format='wav')
    .run_async(pipe_stdin=True, pipe_stdout=True, pipe_stderr=True, quiet=True, overwrite_output=True)
  )
  output, err = process.communicate(input=binary)

  riff_chunk_size = len(output) - 8
  # Break up the chunk size into four bytes, held in b.
  q = riff_chunk_size
  b = []
  for i in range(4):
      q, r = divmod(q, 256)
      b.append(r)

  # Replace bytes 4:8 in proc.stdout with the actual size of the RIFF chunk.
  riff = output[:4] + bytes(b) + output[8:]

  sr, audio = wav_read(io.BytesIO(riff))

  return audio, sr

"""## 🎙️ **Record and Transcribe** [Choose the task]
**NOTE: This block contains the recording system code. You don't need to modify anything here; just run the cell to activate the tool.**
"""

task = "Translate to English" #@param ["Transcript to Language", "Translate to English"]
import numpy as np
import whisper
from scipy.io.wavfile import write
from IPython.display import clear_output

task = "translate" if Tarea == "Translate to English" else "transcribe"

audio, sr = get_audio()
write('record.wav', sr, audio)

!whisper "record.wav" --task {task} --model medium --verbose False

clear_output()
if task == "translate":
  print("-- TRADUCCIÓN A INGLÉS --\n")
else:
  print("-- TRANSCRIPCIÓN A ESPAÑOL --\n")

print(open('record.wav.txt').read())

"""## 👉 Only **transcribe** audio to the original language. RECOMMENDED (X ► X)

"""

# Procesamos el audio exportando el formato .srt principal
!stable-ts "イロハASMR_体験版.mp3" --task translate --model large-v3 --output_dir audio_transcription --output_format srt

"""# 👉 Only translate audio from the original language to English. (X ► English)

"""

!stable-ts "" --task translate --model large-v3 --output_dir audio_transcription

"""# 👉 Sólo traducir audio del idioma original al español. (X ► Español)


**Para audios complejos con muchos susurros WHISPER IA suele fallar bastante en español**

**la forma mas precisa de traduccion en español es generar la transcricpion limpia en japones con whisper**
"""

!stable-ts "[Nombre de archivo.mp3]" --task transcribe --language es --model large-v3 --output_dir audio_transcription